entity GroupType:
    values:
        group:
            ТДБ
            ТШБ
            ТХБ
            ТЛБ
            ТОБ
            ЭЭБ
            ГДБ
            ГИБ
            ГУБ
            ГМБ
            ГСБ
            ГЭБ
            ХЕБ
            ХТБ
            ХББ
            ХХБ
            КМБ
            КББ
            КСБ
            КУБ
            КРБ
            КТС
            ККС
            РКМ
            РРМ
            РИМ
            РГМ
            ИАБ
            ИВБ
            ИКБ
            ИМБ
            ИНБ
            БАС
            БББ
            БИС            
            БСБ
            ББС
            БПБ
            БЭС
            БОС
            БПС
            КВБ            
            КАБ
            УПБ
            УУБ
            УМБ
            УЭБ
            УКБ            
            УНБ
            УЮБ
            УХБ
            ХЕМ
            ХХМ
            ХБМ
            ХТМ
            ХФМ
            ИВМ
            ИКМ
            ИНМ
            ИММ
            БСМ
            ББМ
            БПМ
            БФМ
            РСС
            РРБ
            РИБ
            РКБ
            РГБ
            ЭОС
            ЭЛБ
            ЭНБ
            ЭСБ
            УИМ
            УСМ
            УДМ
            ТСБ
            ЭСМ
            ЭЭМ
            ЭОМ
            ИАМ
            ТДМ
            ТКМ
            ТЛМ
            ТОМ
            ТХМ
            ТШМ
            БФБ
            РСБ
            УКМ
            УЭМ
            УЮМ
            УПМ
            УУМ
            УММ
            КММ
            КСМ
            КРМ
            КУМ
            КБМ
            КАМ
            КВМ
            УДБ
            УИБ
            УСБ
            ГСМ
            ГММ
            ГДМ
            ГЭМ
            ГУМ
            ГИМ
            ТКБ
            ЩАК
            ЩПК
            ЩСК
            ЩИК
            ЩТК
            ЩОК
            ЩКК
            ЩБК


entity DateTimeType:
    values:
        YandexDatetime:
            %lemma
            $YANDEX.DATETIME
        Monday:
            %lemma
            понедельник
        Tuesday:
            %lemma
            вторник
        Wednesday:
            %lemma
            среда
        Thursday:
            %lemma
            четверг
        Friday:
            %lemma
            пятница
        Saturday:
            %lemma
            суббота
        Sunday:
            %lemma
            воскресенье