slots:
    type:
        source: $When
        type: DateTimeType

root:
    ($Amount)? (пар|уроков|занятий)? (в|во|на)? ($When)?;

$Amount:
    %lemma
    расписание
    какие
    сколько
    количество
    пары
    уроки
    занятия

$When:
    $DateTimeType