version: '3.9'

services:
  proxy:
    container_name: voice-helper-proxy
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    volumes:
      - ssl_data:/etc/resty-auto-ssl
    environment:
      ALLOWED_DOMAINS: "${ALLOWED_DOMAINS}"
      SITES: "${ALLOWED_DOMAINS}=backend:8000"

  backend:
    container_name: voice-helper-server
    build:
      context: ./src
      dockerfile: Dockerfile
    environment:
      SCHEDULE_API_URL: ${SCHEDULE_API_URL}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_PORT: ${DATABASE_PORT}
      VK_API_KEY: ${VK_API_KEY}
    depends_on:
      - database
    restart: always

  database:
    container_name: voice-helper-database
    image: postgres:12.2-alpine
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - voice-assistants-postgres-db:/var/lib/postgresql
    restart: always

volumes:
  voice-assistants-postgres-db:
  ssl_data: