name: Build and Test Skills

on:
  pull_request:
    branches:
      - main
      - dev
      - "dev/**"
  push:
    branches:
      - main
      - dev
      - "dev/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd src
          pip install -r requirements.txt
      - name: Test Alice with unittest
        run: |
          python tests.py
